import { html } from '../lib/html.mjs';
import { btn, ctaBand } from '../lib/ui.mjs';
import { wordmark } from '../lib/brand.mjs';

export const meta = {
  id: 'portfolio', section: 'portfolio', title: 'OGC Nice Women — Our Flagship Investment',
  description: 'OGC Nice Women, Freya Sports Partners’ principal investment. Supporting women’s football, player development and a long-term sporting ambition on the French Riviera.',
  headerTheme: 'void',
};

const pillars = [
  ['01', 'Sporting excellence.', 'Back the next generation of players.', 'A long-term focus on talent development, recruitment and the conditions that allow female players and teams to perform.'],
  ['02', 'Commercial ambition.', 'Turn connection into opportunity.', 'Develop partnerships, visibility and a compelling matchday experience for women’s football, grounded in the team’s identity and its Riviera setting.'],
  ['03', 'Lasting foundations.', 'Grow without losing our roots.', 'Support the foundations of the women’s programme: player pathways, the sporting environment and a lasting connection with the local community.'],
];

export function render() {
  return html`
  <section class="nice-hero" data-theme="void" aria-labelledby="nice-title">
    <div class="wrap">
      <div class="nice-hero__top"><nav class="crumbs" aria-label="Breadcrumb"><a href="index.html">Freya</a><span>/</span><span aria-current="page">Portfolio</span></nav><span class="micro">FSP / Flagship investment</span></div>
      <div class="nice-hero__intro"><span class="label nice-label">Our principal investment</span><span class="micro">Women’s football · Nice, France</span></div>
      <div class="nice-hero__head"><h1 id="nice-title">OGC <span>Nice.</span><small>Féminines</small></h1><div class="nice-hero__side"><span class="nice-hero__dash" aria-hidden="true"></span><p>Her game. Our conviction.<br>A shared ambition.</p><a class="link" href="#nice-conviction"><span>Discover our conviction</span><span aria-hidden="true">↓</span></a></div></div>
      <figure class="nice-photo"><img src="assets/img/ogc-nice-team-photo.png" alt="The OGC Nice women’s team and staff gathered together at the club’s training ground." width="2000" height="800" fetchpriority="high"><div class="nice-photo__shade" aria-hidden="true"></div><div class="nice-photo__caption"><span class="micro">Les Aiglonnes / Nice, Côte d’Azur</span><span class="nice-photo__motto">Issa Nissa.</span></div><div class="nice-photo__tag" aria-label="Freya SP × OGC Nice Féminines"><span class="nice-photo__freya">${wordmark()}</span><span class="nice-photo__multiply" aria-hidden="true">×</span><span class="nice-photo__partner"><strong>OGC NICE</strong><small>Féminines</small></span></div></figure>
      <div class="nice-facts"><div><span class="nice-facts__value nice-facts__value--text">Women’s football</span><span class="label">Our core conviction</span></div><div><span class="nice-facts__value nice-facts__value--text">Les Aiglonnes</span><span class="label">The team at the heart of it</span></div><div><span class="nice-facts__value nice-facts__value--text">Nice</span><span class="label">Rooted in the Riviera</span></div><div><span class="nice-facts__value nice-facts__value--text">Rouge & Noir</span><span class="label">An unmistakable identity</span></div></div>
    </div>
  </section>
  <section class="sec nice-conviction" id="nice-conviction" data-theme="ice">
    <div class="wrap nice-editorial"><figure class="nice-editorial__visual"><span class="nice-editorial__backdrop" aria-hidden="true">NICE</span><img src="assets/img/ogc-nice-players-cutout.png" alt="Two smiling OGC Nice women’s players celebrating together in their red and black kit." width="1087" height="1446" loading="lazy"></figure><div class="nice-editorial__body"><div class="nice-editorial__meta"><span class="idx">01 / Conviction</span><span class="label">The heart of our portfolio</span></div><h2 class="h1" data-reveal>Deep roots.<br><span class="dim">A bigger horizon.</span></h2><p class="lead" data-reveal>OGC Nice Women is Freya’s principal investment. It brings our core conviction to life: women’s sport deserves the capital, attention and foundations to realise its potential, on and off the pitch.</p><div class="nice-editorial__columns" data-reveal><p>Les Aiglonnes carry the red and black identity of Nice into women’s football. Their story puts female players, local talent and the next generation of girls at the centre of the sporting project.</p><p>Our ambition is to build on that foundation. To support a women’s team that looks ahead, develops talent and creates lasting value — while keeping its players, its city and its supporters at the centre of the story.</p></div><div class="nice-editorial__signature"><span class="label">Freya Sports Partners</span><span class="micro">Long-term capital. Sporting conviction.</span></div></div></div>
  </section>
  <section class="sec nice-ambition" data-theme="void"><div class="wrap"><div class="nice-ambition__top"><figure class="nice-squad"><span class="nice-squad__backdrop" aria-hidden="true">NICE</span><img src="assets/img/ogc-nice-women-squad-cutout.png" alt="OGC Nice Féminines, the whole team celebrating together on the pitch." width="1672" height="941" loading="lazy"></figure><div class="nice-section-head"><span class="label"><span class="idx">02</span> / Our ambition</span><div class="nice-section-head__copy"><h2 class="h2" data-reveal>More than a season.<br><span class="dim">A lasting sporting project.</span></h2><p class="lead">Three priorities guide our vision for OGC Nice Women.</p></div></div></div><div class="nice-pillars">${pillars.map(([n, title, sub, text]) => html`<article class="nice-pillar" data-reveal><span class="nice-pillar__number">${n}</span><h3 class="h3">${title}</h3><p class="nice-pillar__sub">${sub}</p><p class="body-sm">${text}</p><span class="nice-pillar__line" aria-hidden="true"></span></article>`)}</div></div></section>
  <section class="sec nice-identity" data-theme="dark"><div class="wrap nice-identity__grid"><div class="nice-identity__art" aria-hidden="true"><span class="micro">Nice / Côte d’Azur</span><div class="nice-identity__stripes"></div><span class="nice-identity__year nice-identity__year--women">Elles.</span><span class="label">Le Gym. Les Aiglonnes.</span></div><div class="nice-identity__copy"><span class="label"><span class="idx">03</span> / One club. One city.</span><h2 class="h2" data-reveal>The Riviera.<br>The red and black.<br><span class="dim">The next chapter.</span></h2><p class="lead" data-reveal>A women’s team with a distinctive identity and a city behind it. Our vision for Les Aiglonnes connects sporting ambition with opportunity: for the players on the pitch today and the girls who will follow them.</p><div class="nice-identity__links">${btn('https://www.ogcnice.com/fr/rubrique/feminines', 'Discover Les Aiglonnes', { ico: 'arrowUpRight', target: '_blank', rel: 'noopener noreferrer' })}</div></div></div><div class="wrap nice-credit"><a href="https://www.ogcnice.com/fr/rubrique/feminines" target="_blank" rel="noopener noreferrer">Women’s team photograph: OGC Nice</a></div></section>
  ${ctaBand({label: 'Our principal investment', title: 'Shared ambition.<br><span class="dim">Long-term conviction.</span>', text: 'Discover the investment perspective behind our flagship women’s football project.', primary: ['contact.html', 'Talk to Freya'], secondary: ['investors.html', 'Investor centre']})}`;
}
